version: '3.8'
services:
  db:
    container_name: postgresql_jmp_adv-2-db
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "127.0.0.1:5432:5432"
  java:
    depends_on:
      - db
    container_name: jmp-adv-security-2-java
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
    build:
      dockerfile: Dockerfile
    image: jmp-adv-security-2-app:latest
    ports:
      - "127.0.0.1:8080:8080"

