CREATE TABLE authority
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_authority PRIMARY KEY (id)
);

CREATE TABLE authority_person
(
    authority_id BIGINT NOT NULL,
    person_id    BIGINT NOT NULL,
    CONSTRAINT pk_authority_person PRIMARY KEY (authority_id, person_id)
);

CREATE TABLE person
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE secret
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value VARCHAR(255),
    link  VARCHAR(255),
    CONSTRAINT pk_secret PRIMARY KEY (id)
);

ALTER TABLE authority
    ADD CONSTRAINT uc_authority_name UNIQUE (name);

ALTER TABLE authority_person
    ADD CONSTRAINT fk_autper_on_authority FOREIGN KEY (authority_id) REFERENCES authority (id);

ALTER TABLE authority_person
    ADD CONSTRAINT fk_autper_on_person FOREIGN KEY (person_id) REFERENCES person (id);